#!/usr/bin/env python3
"""Generate pinned, offline CommonMark support data from authoritative inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


COMMONMARK_SECTIONS = {
    "Entity and numeric character references",
    "Setext headings",
    "Indented code blocks",
    "HTML blocks",
    "Link reference definitions",
    "Autolinks",
    "Raw HTML",
}
ENTITY_SNAPSHOT_DATE = "2026-08-26"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate_entities(source: Path, destination: Path) -> None:
    raw = json.loads(source.read_text(encoding="utf-8"))
    entries = []
    for name, details in raw.items():
        if not name.startswith("&") or not name.endswith(";"):
            continue
        entries.append((name[1:-1], details["characters"]))
    entries.sort()

    lines = [
        "// Generated by scripts/generate_commonmark_data.py; do not edit by hand.",
        "// Source: https://html.spec.whatwg.org/entities.json",
        f"// Snapshot retrieved: {ENTITY_SNAPSHOT_DATE}",
        f"// SHA-256: {sha256(source)}",
        "",
        "import Foundation",
        "",
        "enum CommonMarkNamedEntities {",
        f"    static let sourceSnapshotDate = {swift_string(ENTITY_SNAPSHOT_DATE)}",
        f"    static let sourceSHA256 = {swift_string(sha256(source))}",
        "",
        "    static let values: [String: String] = [",
    ]
    lines.extend(
        f"        {swift_string(name)}: {swift_string(value)},"
        for name, value in entries
    )
    lines.extend(["    ]", "}", ""])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")


def generate_tests(source: Path, spec: Path, destination: Path) -> None:
    all_tests = json.loads(source.read_text(encoding="utf-8"))
    selected = [test for test in all_tests if test["section"] in COMMONMARK_SECTIONS]
    payload = {
        "commonmarkVersion": "0.31.2",
        "source": "https://github.com/commonmark/commonmark-spec/tree/0.31.2",
        "specSHA256": sha256(spec),
        "license": "CC-BY-SA-4.0",
        "sections": sorted(COMMONMARK_SECTIONS),
        "examples": selected,
    }
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def generate_all_tests(source: Path, spec: Path, destination: Path) -> None:
    payload = {
        "commonmarkVersion": "0.31.2",
        "source": "https://github.com/commonmark/commonmark-spec/tree/0.31.2",
        "specSHA256": sha256(spec),
        "license": "CC-BY-SA-4.0",
        "examples": json.loads(source.read_text(encoding="utf-8")),
    }
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--entities", type=Path, required=True)
    parser.add_argument("--all-tests", type=Path, required=True)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--entities-output", type=Path, required=True)
    parser.add_argument("--tests-output", type=Path, required=True)
    parser.add_argument("--all-tests-output", type=Path)
    args = parser.parse_args()

    generate_entities(args.entities, args.entities_output)
    generate_tests(args.all_tests, args.spec, args.tests_output)
    if args.all_tests_output is not None:
        generate_all_tests(args.all_tests, args.spec, args.all_tests_output)


if __name__ == "__main__":
    main()
